### ISSUE TITLE
cmake-based macOS template would be great.

### ISSUE THREAD

**Issue by shakfu** [beeware/briefcase-macOS-Xcode-template#16]
This project and the whole beeware ecosystem are great. 

I think it would definitely benefit from a cmake-based template. Would that be something viable?

**Comment by freakboy3742** [comment]
It's not clear to me why a cmake-based template would be beneficial. Apple doesn't (to my knowledge) provide any support for cmake; their entire ecosystem is focussed on Xcode. Furthermore, it's not clear to me what use case would be enabled by adding a second "project"-based app definition for macOS.

Assuming cmake has the tools to build, package, sign and notarize a macOS app (I presume this is possible, but I do not know for certain), adding a cmake-based backend would be entirely possible. However it wouldn't be a variant on this Xcode template. It would be a standalone template with its own Briefcase backend. 

On that basis, I'm going to close this ticket. If you're especially enthused for a cmake backend, I'd suggest writing one as a third party. Briefcase backends are plugins, and third party tools can provide those plugins.

**Comment by shakfu** [comment]
@freakboy3742 Thanks for your reply.

> it's not clear to me what use case would be enabled by adding a second "project"-based app definition for macOS.

Just to be clear, I wasn't suggesting official support for such template, I was merely flagging that such a template would be useful since there are users who prefer using cmake as a build system per se or who use cmake to configure and generate their Xcode projects. This is especially the case if one prefer text-based build configuration over gui-based build configuration.

> it wouldn't be a variant on this Xcode template. It would be a standalone template with its own Briefcase backend... If you're especially enthused for a cmake backend, I'd suggest writing one as a third party. Briefcase backends are plugins, and third party tools can provide those plugins.

I have already started a small [project](https://github.com/shakfu/beeware-python-tests) to see if cmake actually works in this instance. 

Still experimenting and testing. If it proves viable, it may be worthwhile turning into a 'third-party' plugin as you have suggested. As I am not aware what a 'plugin' entails specifically, it is definitely something I should investigate further in any case.

**Comment by freakboy3742** [comment]
FWIW - a standalone plugin would involve:
1. A GitHub repo acting as a cookiecutter template for a project. This is the analog of this project (briefcase-macOS-Xcode-template), except generating a Cmake project.
2. A Python module that [registers a `briefcase.formats.macOS` entry point](https://github.com/beeware/briefcase/blob/main/setup.cfg#L116), exposing a variable matching each of the supported commands (create, build, run etc). You should be able to use an existing backend (e.g., https://github.com/beeware/briefcase/blob/main/src/briefcase/platforms/macOS/xcode.py) as a model for what is needed here. The key pieces you need to implement are the paths to the key pieces (such as the location of the binary that is generated), and the specific command needed to build the project.

**Comment by shakfu** [comment]
Thanks, that's very helpful.
