### ISSUE TITLE
Isolated Python config uses Ascii encoding

### ISSUE THREAD

**Issue by samschott** [beeware/briefcase-macOS-Xcode-template#17]
**Describe the bug**
Now that Python is initialised with an isolated config, it seems to now longer read the LC_CTYPE environment variable which we set in the Info.plist. As a result, it is initialised with Ascii encoding instead of UTF-8.

**To Reproduce**
1. Create and build a default briefcase app with the newest template.
2. Try to print a non-ascii character to the console from the app.

**Environment:**
 - Operating System: macOS
 - Python version: 3.11
 - Software versions:
   - Briefcase: 0.3.12.dev188+g4cac510

**Additional context**
We should probably tell Python to use UTF-8 using in the pre-config:
https://docs.python.org/3/c-api/init_config.html#c.PyPreConfig.utf8_mode

**Comment by mhsmith** [comment]
It might be useful to add a test for this to the [Python-support-testbed](https://github.com/beeware/Python-support-testbed/).
