### ISSUE TITLE
Cannot retrieve traceback without nslog scripts

### ISSUE THREAD

**Issue by samschott** [beeware/briefcase-macOS-Xcode-template#7]
**Describe the bug**
Currently, retrieving the traceback from an unhandled Python exceptions and displayed it in an error dialog relies on `sys._traceback` being set. `sys._traceback` is set by the `nslog` pyhton script which is no longer required by briefcase since fixing https://github.com/beeware/briefcase/issues/675. If a user chooses not to install it, any Python exceptions will generate the unhelpful error message `Could not access sys._traceback`.

**To Reproduce**
1. Create a briefcase project without the std-nslog dependency.
2. Trigger an unhandled exception.

**Expected behavior**
Show the actual traceback instead.

**Environment:**
 - Operating System: macOS
 - Python version: 3.7 to 3.10

**Additional context**
Ideally, we would use the CPython API to retrieve and format the traceback even when std-nslog is not installed.

**Comment by freakboy3742** [comment]
It's not completely true to say the NSLog script is no longer required - it's still needed to redirect stdout/err to NSLog.

**Comment by freakboy3742** [comment]
Resolved by #8
